# Generated by Django 5.2.3 on 2025-07-08 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_projects'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='projects',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tasks.projects'),
        ),
    ]
